### ISSUE TITLE
Collectd 5.7 - Plugin not sending any data

### ISSUE THREAD

**Issue by LaurentDumont** [Yuav/collectd-iscdhcp#1]
Hi!

Super cool plugin and I'd love to be able to use it with Grafana. Unfortunately, it seems that it's not working with my current setup of collectd.

The collectd config block looks like this : 

```
LoadPlugin python

<Plugin python>
  ModulePath "/usr/local/lib/python2.7/dist-packages/collectd_iscdhcp/"
  Interactive false
  Import "collectd_iscdhcp"
  LogTraces true
</Plugin>
```

Everything looks like it loads correctly but it seems that no stats are sent to my influxDB instance. I have tried running the python script manually but as the collectd module is not accessible externally, I have had a hard-time troubleshooting the issue. I do see that other plugins are sending data to influxDB correctly so it seems okay on that side.

Is there a more verbose log setting I can enable somewhere? I'd like to see the output from the python module itself.

Thank you

**Comment by jskarpe** [comment]
This plugins is just a wrapper/parser around the output from dhcpd-pools found in the bin folder. It's executed here: https://github.com/Yuav/collectd-iscdhcp/blob/master/collectd_iscdhcp/collectd_plugin.py#L17 

I would suggest you try and run dhcpd-pools manually to figure out what's going on

**Comment by skob** [comment]
use:
```
Import "collectd_iscdhcp.collectd_plugin"
```
